channels:
  - conda-forge
dependencies:
  - python>=3.7,<=3.11
  - pathlib
  - typing
  - pytest  # only required for running tests
  - pytest-cov  # only required for running tests coverage
  - black
  - isort